<a href="https://colab.research.google.com/github/Praxis-QR/FDS/blob/main/Data_Dumps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://github.com/Praxis-QR/RDWH/raw/main/images/YantraJaalBanner.png)<br>


<hr>

[Prithwis Mukerjee](http://www.linkedin.com/in/prithwis)<br>

# 00 Collection of Useful Data Sets

In [1]:
from datetime import datetime
import pytz
print('ॐ श्री सरस्वत्यै नमः',datetime.now(pytz.timezone('Asia/Calcutta')))
!python --version
!lsb_release -a
#
import pandas as pd

ॐ श्री सरस्वत्यै नमः 2025-08-24 21:43:53.755971+05:30
Python 3.12.11
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

# 01 eCommerce Data - 500K rows

In [2]:
!wget -q -O eCommerce.zip https://github.com/Praxis-QR/FDS/raw/refs/heads/main/DataDump%202025/eCommerce_541Kx8.zip
eCommerce_df = pd.read_csv("eCommerce.zip", encoding = 'ISO-8859-1')
eCommerce_df.shape

(541909, 8)

In [3]:
eCommerce_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [4]:
eCommerce_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [5]:
# change the invoice_date format - String to Timestamp format
eCommerce_df['InvoiceDate'] = pd.to_datetime(eCommerce_df.InvoiceDate, format='%m/%d/%Y %H:%M')
# for more data cleaning see here https://github.com/Praxis-QR/PythonForManagers/blob/main/Appendix_eCommerce_Version_21_12.ipynb

In [7]:
eCommerce_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

# 02 SuperStore Sales Data ~ 50K rows

In [8]:
!wget -q -O SuperStore.zip https://github.com/Praxis-QR/FDS/raw/refs/heads/main/DataDump%202025/SuperStoreSalesKaggle_51290x21.zip
SuperStore_df = pd.read_csv("SuperStore.zip")
SuperStore_df.shape

(51290, 21)

In [9]:
!wget -q -O SuperStore.xls https://github.com/Praxis-QR/FDS/raw/refs/heads/main/DataDump%202025/KaggleRetailSales_51290x21.xlsx
SuperStore2_df = pd.read_excel("SuperStore.xls")
SuperStore2_df.shape

(51290, 21)

In [10]:
SuperStore_df.equals(SuperStore2_df)

False

In [11]:
SuperStore_df.compare(SuperStore2_df)

      order_date       ship_date            sales
            self other      self      other  self other
0            NaN   NaT  6/1/2011 2011-01-06   408   408
1            NaN   NaT  8/1/2011 2011-01-08   120   120
2            NaN   NaT  5/1/2011 2011-01-05    66    66
3            NaN   NaT  5/1/2011 2011-01-05    45    45
4            NaN   NaT  8/1/2011 2011-01-08   114   114
...          ...   ...       ...        ...   ...   ...
51285        NaN   NaT  4/1/2015 2015-01-04    14    14
51286        NaN   NaT  5/1/2015 2015-01-05     4     4
51287        NaN   NaT  2/1/2015 2015-01-02    26    26
51288        NaN   NaT  6/1/2015 2015-01-06     7     7
51289        NaN   NaT  4/1/2015 2015-01-04     3     3

[51290 rows x 6 columns]

In [12]:
SuperStore_df.head(3)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011

In [13]:
SuperStore_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  object
 2   ship_date       51290 non-null  object
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  object
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), object(16)
memory usage: 8.2+ MB

In [14]:
SuperStore2_df.head(3)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011

In [15]:
SuperStore2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  datetime64[ns]
 2   ship_date       51290 non-null  datetime64[ns]
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  int64
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 8.2+ MB

# 03 SuperStore Data ~ 10K

In [16]:
!wget -q -O SS1_df.xls https://github.com/Praxis-QR/FDS/raw/refs/heads/main/DataDump%202025/Superstore_9924x21.xls
SS1_df = pd.read_excel("SS1_df.xls")
SS1_df.shape

(9994, 21)

In [17]:
!wget -q -O SS2.csv https://github.com/Praxis-QR/FDS/raw/refs/heads/main/DataDump%202025/SuperstoreData_9924x21.csv
SS2_df = pd.read_csv("SS2.csv")
SS2_df.shape

(9994, 21)

In [18]:
SS1_df.equals(SS2_df)

False

In [19]:
SS1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [20]:
SS2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

# 04 Sales Data ~ 88K

In [21]:
!wget -q -O Sales.csv https://github.com/Praxis-QR/FDS/raw/refs/heads/main/DataDump%202025/SalesData_88475x11.csv
Sales_df = pd.read_csv("Sales.csv")
Sales_df.shape

(88475, 11)

In [22]:
Sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88475 entries, 0 to 88474
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Retailer country   88475 non-null  object
 1   Order method type  88475 non-null  object
 2   Retailer type      88475 non-null  object
 3   Product line       88475 non-null  object
 4   Product type       88475 non-null  object
 5   Product            88475 non-null  object
 6   Year               88475 non-null  int64
 7   Quarter            88475 non-null  object
 8   Revenue            88475 non-null  float64
 9   Quantity           88475 non-null  int64
 10  Gross margin       87894 non-null  float64
dtypes: float64(2), int64(2), object(7)
memory usage: 7.4+ MB

In [23]:
Sales_df.head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
0,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Deluxe Cook Set,2012,Q1 2012,59628.66,489,0.347548
1,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Double Flame,2012,Q1 2012,35950.32,252,0.474274
2,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Dome,2012,Q1 2012,89940.48,147,0.352772
3,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Gazer 2,2012,Q1 2012,165883.41,303,0.282938
4,United States,Fax,Outdoors Shop,Camping Equipment,Sleeping Bags,Hibernator Lite,2012,Q1 2012,119822.20,1415,0.291450

# 05 IMDB Top 1000

In [24]:
!wget -q -O IMDB1000.csv https://raw.githubusercontent.com/Praxis-QR/FDS/refs/heads/main/DataDump%202025/IMDB_Top_1000x16.csv
imdb_df = pd.read_csv("IMDB1000.csv")
imdb_df.shape

(1000, 16)

In [25]:
imdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [26]:
imdb_df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

# 06 IMDB Other

In [27]:
!wget -q -O movies.xls https://github.com/Praxis-QR/FDS/raw/refs/heads/main/DataDump%202025/IMDB_Movies_1338x25.xls
imdb2_df = pd.read_excel("movies.xls")
imdb2_df.shape

(1338, 25)

In [28]:
imdb2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Title                        1338 non-null   object
 1   Year                         1338 non-null   int64
 2   Genres                       1338 non-null   object
 3   Language                     1333 non-null   object
 4   Country                      1338 non-null   object
 5   Content Rating               1316 non-null   object
 6   Duration                     1338 non-null   int64
 7   Aspect Ratio                 1308 non-null   float64
 8   Budget                       1281 non-null   float64
 9   Gross Earnings               1086 non-null   float64
 10  Director                     1338 non-null   object
 11  Actor 1                      1338 non-null   object
 12  Actor 2                      1338 non-null   object
 13  Actor 3                      1336 non-null   object
 14  Facebook Likes - Director    1338 non-null   int64
 15  Facebook Likes - Actor 1     1338 non-null   int64
 16  Facebook Likes - Actor 2     1338 non-null   int64
 17  Facebook Likes - Actor 3     1336 non-null   float64
 18  Facebook Likes - cast Total  1338 non-null   int64
 19  Facebook likes - Movie       1338 non-null   int64
 20  Facenumber in posters        1338 non-null   int64
 21  User Votes                   1338 non-null   int64
 22  Reviews by Users             1338 non-null   int64
 23  Reviews by Crtiics           1335 non-null   float64
 24  IMDB Score                   1338 non-null   float64
dtypes: float64(6), int64(10), object(9)
memory usage: 261.5+ KB

In [29]:
imdb2_df.head()

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
0,Intolerance: Love's Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907.0,NaN,...,436,22,9.0,481,691,1,10718,88,69.0,8.0
1,Over the Hill to the Poorhouse,1920,Crime|Drama,NaN,USA,NaN,110,1.33,100000.0,3000000.0,...,2,2,0.0,4,0,1,5,1,1.0,4.8
2,The Big Parade,1925,Drama|Romance|War,NaN,USA,Not Rated,151,1.33,245000.0,NaN,...,81,12,6.0,108,226,0,4849,45,48.0,8.3
3,Metropolis,1927,Drama|Sci-Fi,German,Germany,Not Rated,145,1.33,6000000.0,26435.0,...,136,23,18.0,203,12000,1,111841,413,260.0,8.3
4,Pandora's Box,1929,Crime|Drama|Romance,German,Germany,Not Rated,110,1.33,NaN,9950.0,...,426,20,3.0,455,926,1,7431,84,71.0,8.0

# 07 NYC Listing ~ 50K

In [30]:
!wget -q -O nyc.csv https://github.com/Praxis-QR/FDS/raw/refs/heads/main/DataDump%202025/NYC_Listing_48903x16.csv
nyc_df = pd.read_csv("nyc.csv")
nyc_df.shape

(48903, 16)

In [31]:
nyc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48903 entries, 0 to 48902
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48903 non-null  int64
 1   name                            48887 non-null  object
 2   host_id                         48903 non-null  int64
 3   host_name                       48882 non-null  object
 4   neighbourhood_group             48903 non-null  object
 5   neighbourhood                   48903 non-null  object
 6   latitude                        48903 non-null  float64
 7   longitude                       48903 non-null  float64
 8   room_type                       48903 non-null  object
 9   price                           48903 non-null  int64
 10  minimum_nights                  48903 non-null  int64
 11  number_of_reviews               48903 non-null  int64
 12  last_review                     38850 non-null  object
 13  reviews_per_month               38850 non-null  float64
 14  calculated_host_listings_count  48903 non-null  int64
 15  availability_365                48903 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [32]:
nyc_df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0

# 08 Articles Read

In [33]:
#dataURL = 'https://raw.githubusercontent.com/Praxis-QR/FDS/main/data/pandas_tutorial_read.csv'
!wget -q -O ArticlesRead.csv https://github.com/Praxis-QR/FDS/raw/refs/heads/main/DataDump%202025/Articles_Read_1795x6.csv
colNames = ['my_datetime', 'event', 'country', 'user_id', 'source', 'topic']
ArticlesRead_df = pd.read_csv('ArticlesRead.csv', delimiter=';', names = colNames )
ArticlesRead_df.shape

(1795, 6)

In [34]:
ArticlesRead_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1795 entries, 0 to 1794
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   my_datetime  1795 non-null   object
 1   event        1795 non-null   object
 2   country      1795 non-null   object
 3   user_id      1795 non-null   int64
 4   source       1795 non-null   object
 5   topic        1795 non-null   object
dtypes: int64(1), object(5)
memory usage: 84.3+ KB

In [35]:
ArticlesRead_df.head()

           my_datetime event    country     user_id   source          topic
0  2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
1  2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
2  2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
3  2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
4  2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America

# 09 Pokemon

In [36]:
!wget -q -O Pokemon.csv https://github.com/Praxis-QR/FDS/raw/refs/heads/main/DataDump%202025/Pokemon_151x12.csv
pokemon_df = pd.read_csv('Pokemon.csv', index_col=0, encoding='latin')
pokemon_df.shape

(151, 12)

In [37]:
pokemon_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 151 entries, 1 to 151
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       151 non-null    object
 1   Type 1     151 non-null    object
 2   Type 2     67 non-null     object
 3   Total      151 non-null    int64
 4   HP         151 non-null    int64
 5   Attack     151 non-null    int64
 6   Defense    151 non-null    int64
 7   Sp. Atk    151 non-null    int64
 8   Sp. Def    151 non-null    int64
 9   Speed      151 non-null    int64
 10  Stage      151 non-null    int64
 11  Legendary  151 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 14.3+ KB

In [38]:
pokemon_df.head()

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Stage,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,2,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,3,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,2,False

# 10 FAO Data

In [39]:
!wget -O FAO.csv -q 'https://github.com/Praxis-QR/FDS/raw/refs/heads/main/DataDump%202025/FAO_21477x63.csv'
fao_df = pd.read_csv('FAO.csv',encoding='latin')
fao_df.shape

(21477, 63)

In [40]:
fao_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21477 entries, 0 to 21476
Data columns (total 63 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Area Abbreviation  21356 non-null  object
 1   Area Code          21477 non-null  int64
 2   Area               21477 non-null  object
 3   Item Code          21477 non-null  int64
 4   Item               21477 non-null  object
 5   Element Code       21477 non-null  int64
 6   Element            21477 non-null  object
 7   Unit               21477 non-null  object
 8   latitude           21477 non-null  float64
 9   longitude          21477 non-null  float64
 10  Y1961              17938 non-null  float64
 11  Y1962              17938 non-null  float64
 12  Y1963              17938 non-null  float64
 13  Y1964              17938 non-null  float64
 14  Y1965              17938 non-null  float64
 15  Y1966              17938 non-null  float64
 16  Y1967              17938 non-null  float64
 17  Y1968              17938 non-null  float64
 18  Y1969              17938 non-null  float64
 19  Y1970              17938 non-null  float64
 20  Y1971              17938 non-null  float64
 21  Y1972              17938 non-null  float64
 22  Y1973              17938 non-null  float64
 23  Y1974              17938 non-null  float64
 24  Y1975              17938 non-null  float64
 25  Y1976              17938 non-null  float64
 26  Y1977              17938 non-null  float64
 27  Y1978              17938 non-null  float64
 28  Y1979              17938 non-null  float64
 29  Y1980              17938 non-null  float64
 30  Y1981              17938 non-null  float64
 31  Y1982              17938 non-null  float64
 32  Y1983              17938 non-null  float64
 33  Y1984              17938 non-null  float64
 34  Y1985              17938 non-null  float64
 35  Y1986              17938 non-null  float64
 36  Y1987              17938 non-null  float64
 37  Y1988              17938 non-null  float64
 38  Y1989              17938 non-null  float64
 39  Y1990              18062 non-null  float64
 40  Y1991              18062 non-null  float64
 41  Y1992              20490 non-null  float64
 42  Y1993              20865 non-null  float64
 43  Y1994              20865 non-null  float64
 44  Y1995              20865 non-null  float64
 45  Y1996              20865 non-null  float64
 46  Y1997              20865 non-null  float64
 47  Y1998              20865 non-null  float64
 48  Y1999              20865 non-null  float64
 49  Y2000              21128 non-null  float64
 50  Y2001              21128 non-null  float64
 51  Y2002              21128 non-null  float64
 52  Y2003              21128 non-null  float64
 53  Y2004              21128 non-null  float64
 54  Y2005              21128 non-null  float64
 55  Y2006              21373 non-null  float64
 56  Y2007              21373 non-null  float64
 57  Y2008              21373 non-null  float64
 58  Y2009              21373 non-null  float64
 59  Y2010              21373 non-null  float64
 60  Y2011              21373 non-null  float64
 61  Y2012              21477 non-null  int64
 62  Y2013              21477 non-null  int64
dtypes: float64(53), int64(5), object(5)
memory usage: 10.3+ MB

In [41]:
fao_df.head()

,Area Abbreviation,Area Code,Area,Item Code,Item,Element Code,Element,Unit,latitude,longitude,...,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013
0,AF,2,Afghanistan,2511,Wheat and products,5142,Food,1000 tonnes,33.94,67.71,...,3249.0,3486.0,3704.0,4164.0,4252.0,4538.0,4605.0,4711.0,4810,4895
1,AF,2,Afghanistan,2805,Rice (Milled Equivalent),5142,Food,1000 tonnes,33.94,67.71,...,419.0,445.0,546.0,455.0,490.0,415.0,442.0,476.0,425,422
2,AF,2,Afghanistan,2513,Barley and products,5521,Feed,1000 tonnes,33.94,67.71,...,58.0,236.0,262.0,263.0,230.0,379.0,315.0,203.0,367,360
3,AF,2,Afghanistan,2513,Barley and products,5142,Food,1000 tonnes,33.94,67.71,...,185.0,43.0,44.0,48.0,62.0,55.0,60.0,72.0,78,89
4,AF,2,Afghanistan,2514,Maize and products,5521,Feed,1000 tonnes,33.94,67.71,...,120.0,208.0,233.0,249.0,247.0,195.0,178.0,191.0,200,200

#Chronobooks <br>
Three science fiction novels by Prithwis Mukerjee. A dystopian Earth. A technocratic society managed by artificial intelligence. Escape and epiphany on Mars. Can man and machine, carbon and silicon explore and escape into other dimensions of existence? An Indic perspective rooted in Advaita Vedanta and the Divine Feminine.  [More information](http://bit.ly/chrono3) <br>
![alt text](https://blogger.googleusercontent.com/img/a/AVvXsEjsZufX_KYaLwAnJP6bUxvDg5RSPn6r8HIZe749nLWX3RuwyshrYEAUpdw03a9WIWRdnzA9epwJOE05eDJ0Ad7kGyfWiUrC2vNuOskb2jA-e8aOZSx8YqzT8mfZi3E4X1Rz3qlEAiv-aTxlCM976BEeTjx4J64ctY3C_FoV4v9aY_U23F8xRqI5Eg=s1600)