<a href="https://colab.research.google.com/github/Praxis-QR/FDS/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![CC-BY-SA](https://licensebuttons.net/l/by-sa/3.0/88x31.png)<br>
<hr>

![alt text](https://github.com/Praxis-QR/RDWH/raw/main/images/YantraJaalBanner.png)<br>


<hr>

[Prithwis Mukerjee](http://www.linkedin.com/in/prithwis)<br>

#Data Cleaning
[Original Tutorial](https://www.shiksha.com/online-courses/articles/data-cleaning-using-pandas/) <br>
[Saved File](https://github.com/Praxis-QR/FDS/blob/main/Docs/DataCleaningTutorial.pdf)

In [2]:
import pandas as pd

In [1]:
!wget -q -O data.csv https://github.com/Praxis-QR/FDS/raw/main/data/AB_NYC.csv

In [9]:
#Importing the dataset by reading the csv file
#df = pd.read_csv('AB_NYC_2019.csv')
df0 = pd.read_csv('data.csv')
df0.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0

In [10]:
#First look at the data
#
df0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48903 entries, 0 to 48902
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48903 non-null  int64
 1   name                            48887 non-null  object
 2   host_id                         48903 non-null  int64
 3   host_name                       48882 non-null  object
 4   neighbourhood_group             48903 non-null  object
 5   neighbourhood                   48903 non-null  object
 6   latitude                        48903 non-null  float64
 7   longitude                       48903 non-null  float64
 8   room_type                       48903 non-null  object
 9   price                           48903 non-null  int64
 10  minimum_nights                  48903 non-null  int64
 11  number_of_reviews               48903 non-null  int64
 12  last_review                     38850 non-null  object
 13  reviews_per_month               38850 non-null  float64
 14  calculated_host_listings_count  48903 non-null  int64
 15  availability_365                48903 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [11]:
#Finding duplicated values in a DataFrame
#Difficult to find
df0.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
48898    False
48899    False
48900    False
48901    False
48902    False
Length: 48903, dtype: bool

In [12]:
#Finding duplicated values in a DataFrame
#Check if any are duplicate
df0.duplicated().any()

True

In [13]:
#Finding duplicated values in a DataFrame
#Check if any are duplicate
df0[df0.duplicated]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
4303,2862900,Charming & Bright Studio @ W 50's,3716641,Ofer,Manhattan,Hell's Kitchen,40.76634,-73.98719,Entire home/apt,99,30,8,09-07-2018,0.19,8,139
4304,2863223,Cozy Room with Private Entrance,14586041,Louie,Brooklyn,Williamsburg,40.70665,-73.95067,Private room,75,7,18,12-08-2015,0.31,1,87
4305,2863408,Newly Renovated Modern 1-Bed Studio,13347167,AFI Apartments,Manhattan,Upper East Side,40.77233,-73.95627,Entire home/apt,103,30,3,07-04-2018,0.06,29,336
4306,2863530,APPARTEMENT 2 CHAMBRES ASTORIA NY,14636480,Ilda,Queens,Astoria,40.77182,-73.93129,Entire home/apt,130,4,56,15-06-2019,1.55,1,0
4307,2863589,Entire Private Modern Studio UPW Manhattan,3716641,Ofer,Manhattan,Upper West Side,40.79193,-73.97443,Entire home/apt,109,30,20,07-06-2019,0.34,8,90
4308,2863696,Live in a doll factory!,5229579,Ryan,Brooklyn,Williamsburg,40.71960,-73.96335,Private room,95,3,0,NaN,NaN,3,0
4309,2864637,Ting Ting's Home in Heart of Brklyn,14641776,Ting,Brooklyn,Fort Greene,40.69053,-73.97910,Entire home/apt,100,5,3,01-05-2015,0.05,1,0
4310,2865117,Huge and beautiful Park Slope Apt,3543836,Glenn,Brooklyn,Park Slope,40.66977,-73.98305,Entire home/apt,155,29,5,31-08-2017,0.08,1,59

In [14]:
#df.drop_duplicates(subset=None, keep='first', inplace=False, ignore_index=False)
#df.drop_duplicates(subset=None, keep='first', inplace=True, ignore_index=False)
df1 = df0.drop_duplicates(subset=None, keep='first', ignore_index=False)

In [15]:
#Finding duplicated values in a DataFrame
df1.duplicated().any()

False

In [16]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48895 entries, 0 to 48902
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.3+ MB

In [17]:
#Finding missing values in a DataFrame
df1.isnull()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48898,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
48899,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
48900,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
48901,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
48902,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False

In [18]:
#Finding missing values in a DataFrame
df1.isna()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48898,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
48899,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
48900,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
48901,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
48902,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False

In [19]:
#Finding missing values in a DataFrame
#Which values are missing
#
df1.isna().any()

id                                False
name                               True
host_id                           False
host_name                          True
neighbourhood_group               False
neighbourhood                     False
latitude                          False
longitude                         False
room_type                         False
price                             False
minimum_nights                    False
number_of_reviews                 False
last_review                        True
reviews_per_month                  True
calculated_host_listings_count    False
availability_365                  False
dtype: bool

In [20]:
#Finding missing values in a DataFrame
#How many values are missing

df1.isna().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [22]:
#Replacing N/A values in a DataFrame
#df.fillna({'name':'Not Stated','host_name':'Not Stated','last_review':0}, inplace=True)
#df1.fillna({'name':'Not Stated','host_name':'Not Stated','last_review':'1-1-1900','reviews_per_month':0}, inplace=True)
df2 = df1.fillna({'name':'Not Stated','host_name':'Not Stated','last_review':'1-1-1900','reviews_per_month':0})

In [ ]:
#19-10-2018

In [23]:
df2.isna().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [24]:
#Dropping columns in a DataFrame
df2.drop(['reviews_per_month'], axis = 1, inplace=True)

In [25]:
df2.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'calculated_host_listings_count', 'availability_365'],
      dtype='object')

In [27]:
#Check if all review IDs are unique
#Changing the index of a DataFrame
#df['id'].is_unique    # original dataframe, not unique
df2['id'].is_unique    # current dataframe, unique

True

In [28]:
#Let’s set the 'id' column as index using set_index:
df2 = df2.set_index('id')
df2.head()

,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,calculated_host_listings_count,availability_365
id,,,,,,,,,,,,,,
2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,6,365
2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,2,355
3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,1-1-1900,1,365
3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,1,194
5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,1,0

In [29]:
df2.iloc[4]

name                              Entire Apt: Spacious Studio/Loft by central park
host_id                                                                       7192
host_name                                                                    Laura
neighbourhood_group                                                      Manhattan
neighbourhood                                                          East Harlem
latitude                                                                  40.79851
longitude                                                                -73.94399
room_type                                                          Entire home/apt
price                                                                           80
minimum_nights                                                                  10
number_of_reviews                                                                9
last_review                                                             19-11-2018
calculated_host_listings_count                                                   1
availability_365                                                                 0
Name: 5022, dtype: object

In [30]:
#Renaming column of a DataFrame
new_col = {'name':'listing_name', 'number_of_reviews':'reviews'}

df2.rename(columns=new_col, inplace=True)
df2.head()

,listing_name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,reviews,last_review,calculated_host_listings_count,availability_365
id,,,,,,,,,,,,,,
2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,6,365
2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,2,355
3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,1-1-1900,1,365
3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,1,194
5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,1,0

In [31]:
df2['last_review'].dtype.type

numpy.object_

In [33]:
#Converting data type
df2['last_review'] = pd.to_datetime(df2['last_review'], format='%d-%m-%Y')
df2['last_review'].dtype.type

numpy.datetime64

In [34]:
#Converting data type to reduce memory
df2['host_id'] = df['host_id'].astype('int32')
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48895 entries, 2539 to 36487245
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   listing_name                    48895 non-null  object
 1   host_id                         192 non-null    float64
 2   host_name                       48895 non-null  object
 3   neighbourhood_group             48895 non-null  object
 4   neighbourhood                   48895 non-null  object
 5   latitude                        48895 non-null  float64
 6   longitude                       48895 non-null  float64
 7   room_type                       48895 non-null  object
 8   price                           48895 non-null  int64
 9   minimum_nights                  48895 non-null  int64
 10  reviews                         48895 non-null  int64
 11  last_review                     48895 non-null  datetime64[ns]
 12  calculated_host_listings_count  48895 non-null  int64
 13  availability_365                48895 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(5), object(5)
memory usage: 5.6+ MB